# Generated by Django 5.1.5 on 2025-01-24 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qna", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="userinterest",
        #     name="user",
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="interests",
        #         to=settings.AUTH_USER_MODEL,
        #     ),
        # ),
        migrations.AddField(
            model_name="userquiz",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="qna.quiz",
            ),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
