# Generated by Django 5.0.3 on 2024-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_answer_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(related_name="questions", to="qna.category"),
        ),
    ]
