# Generated by Django 5.1.5 on 2025-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_rename_userquiz_quizresult_alter_quizresult_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="answers",
            field=models.JSONField(default=list),
        ),
    ]
