# Generated by Django 5.1.5 on 2025-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_quizresult_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="percentage",
            field=models.FloatField(default=0),
        ),
    ]
