# Generated by Django 5.0.3 on 2024-04-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_answer_answer_image_question_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="qna.tag"
            ),
        ),
    ]
