# Generated by Django 5.1.5 on 2025-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0005_quizresult_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="category",
            field=models.CharField(default="Random", max_length=100),
        ),
    ]
