# Generated by Django 5.0.3 on 2024-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0005_alter_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.TextField(blank=True, null=True),
        ),
    ]
