# Generated by Django 5.0.3 on 2024-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0006_question_hint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "questions",
                    models.ManyToManyField(related_name="quizzes", to="qna.question"),
                ),
            ],
        ),
    ]
