# Generated by Django 5.1.5 on 2025-01-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0007_alter_quizresult_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="qna.category",
            ),
            preserve_default=False,
        ),
    ]
