# Generated by Django 5.1.5 on 2025-01-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0008_quiz_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="qna.category",
            ),
        ),
    ]
