# Generated by Django 5.1.5 on 2025-01-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0010_quiz_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInterest",
        ),
    ]
