# Generated by Django 5.0.3 on 2024-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0010_question_answer_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="weightage",
            field=models.FloatField(default=1.0),
        ),
    ]
