# Generated by Django 5.0.3 on 2024-04-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0011_question_weightage"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=50,
            ),
        ),
    ]
