# Generated by Django 5.0 on 2025-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0013_quiz_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
