# Generated by Django 5.1.5 on 2025-01-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0014_userquiz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userquiz",
            options={"verbose_name_plural": "User Quizzes"},
        ),
    ]
