# Generated by Django 5.1.5 on 2025-01-26 15:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name_plural": "Blog Categories"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
