# Generated by Django 5.1.5 on 2025-01-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogcategory_options_alter_blog_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(related_name="blogs", to="blog.blogcategory"),
        ),
    ]
