# Generated by Django 5.0 on 2025-02-06 19:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_slug_alter_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="content",
        ),
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog_section_upload_path"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="blog_section_upload_path"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
    ]
