# Generated by Django 5.0 on 2025-02-06 19:23

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_blog_content_blogsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsection",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.blog.models.blog_section_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="blogsection",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.blog.models.blog_section_upload_path,
            ),
        ),
    ]
