# Generated by Django 5.0 on 2025-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogsection_image_alter_blogsection_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsection",
            name="image_alt",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="blogsection",
            name="image_label",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
