# Generated by Django 5.0 on 2025-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogsection_image_alt_blogsection_image_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
