# Generated by Django 5.1.5 on 2025-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0011_delete_userinterest"),
        ("users", "0002_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(related_name="users", to="qna.category"),
        ),
    ]
