# Generated by Django 5.0 on 2025-02-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevisit",
            name="url",
        ),
    ]
