# Generated by Django 5.0 on 2025-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_remove_pagevisit_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevisit",
            name="page",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
