# Generated by Django 5.0 on 2025-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_pagevisit_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="obj_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
