# Generated by Django 5.0 on 2025-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_pagevisit_obj_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="url",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
