# Generated by Django 5.0 on 2025-02-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_pagevisit_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
