# Generated by Django 5.0 on 2025-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_pagevisit_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="query_params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
